spring:
  application:
    name: school-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bnaqica/school-config
          skipSslValidation: true

server:
  port: 8888